name: Build and deploy redioteka frontend

on:
  push:
    branches: [main, configure_CI/CD_RT-169]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Upload build result
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: ./src/dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build
        uses: actions/download-artifact@v1
        with:
          name: build

      - name: Transfer build files to server
        uses: appleboy/scp-action@master
        with:
          host: 89.208.198.192
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          source: "build"
          target: "/home/ubuntu/frontend/2021_1_RedTech/src/dist"
